import { UserType } from '@prisma/client';

// Teacher role permissions
export const TEACHER_ROLE_PERMISSIONS = {
  // Class Teacher specific permissions
  CLASS_TEACHER_ACCESS: 'teacher.class.all_access',
  CLASS_TEACHER_GRADE_OVERRIDE: 'teacher.grade.override',

  // Subject Teacher specific permissions
  SUBJECT_TEACHER_ACCESS: 'teacher.subject.access',
  SUBJECT_TEACHER_GRADE: 'teacher.grade.subject',
} as const;

export const ACADEMIC_CYCLE_PERMISSIONS = {
  // Institution Level
  MANAGE_ACADEMIC_CYCLES: 'academic_cycle.manage',
  VIEW_ALL_ACADEMIC_CYCLES: 'academic_cycle.view.all',

  // Campus Level
  MANAGE_CAMPUS_ACADEMIC_CYCLES: 'academic_cycle.campus.manage',
  VIEW_CAMPUS_ACADEMIC_CYCLES: 'academic_cycle.campus.view',

  // Class Level
  VIEW_CLASS_ACADEMIC_CYCLES: 'academic_cycle.class.view',
} as const;

// Social Wall permissions
export const SOCIAL_WALL_PERMISSIONS = {
  // Post permissions
  CREATE_POST: 'social_wall.post.create',
  CREATE_ACHIEVEMENT_POST: 'social_wall.achievement_post.create',
  UPDATE_POST: 'social_wall.post.update',
  DELETE_POST: 'social_wall.post.delete',
  VIEW_POSTS: 'social_wall.post.view',

  // Comment permissions
  CREATE_COMMENT: 'social_wall.comment.create',
  UPDATE_COMMENT: 'social_wall.comment.update',
  DELETE_COMMENT: 'social_wall.comment.delete',
  VIEW_COMMENTS: 'social_wall.comment.view',

  // Reaction permissions
  ADD_REACTION: 'social_wall.reaction.add',
  REMOVE_REACTION: 'social_wall.reaction.remove',

  // User interaction permissions
  TAG_USERS: 'social_wall.user.tag',

  // Moderation permissions
  MODERATE_CONTENT: 'social_wall.moderate',
  VIEW_MODERATION_LOGS: 'social_wall.moderation.logs.view',
} as const;

// Role-based permission mappings
export const ROLE_PERMISSIONS = {
  // System Level
  SYSTEM_ADMIN: [
    ACADEMIC_CYCLE_PERMISSIONS.MANAGE_ACADEMIC_CYCLES,
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_ALL_ACADEMIC_CYCLES,
    // Social Wall - Full access
    SOCIAL_WALL_PERMISSIONS.CREATE_POST,
    SOCIAL_WALL_PERMISSIONS.CREATE_ACHIEVEMENT_POST,
    SOCIAL_WALL_PERMISSIONS.UPDATE_POST,
    SOCIAL_WALL_PERMISSIONS.DELETE_POST,
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.CREATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.UPDATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.DELETE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
    SOCIAL_WALL_PERMISSIONS.TAG_USERS,
    SOCIAL_WALL_PERMISSIONS.MODERATE_CONTENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_MODERATION_LOGS,
  ] as const,

  SYSTEM_MANAGER: [
    ACADEMIC_CYCLE_PERMISSIONS.MANAGE_ACADEMIC_CYCLES,
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_ALL_ACADEMIC_CYCLES,
    // Social Wall - Full access
    SOCIAL_WALL_PERMISSIONS.CREATE_POST,
    SOCIAL_WALL_PERMISSIONS.CREATE_ACHIEVEMENT_POST,
    SOCIAL_WALL_PERMISSIONS.UPDATE_POST,
    SOCIAL_WALL_PERMISSIONS.DELETE_POST,
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.CREATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.UPDATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.DELETE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
    SOCIAL_WALL_PERMISSIONS.TAG_USERS,
    SOCIAL_WALL_PERMISSIONS.MODERATE_CONTENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_MODERATION_LOGS,
  ] as const,

  // Institution Level
  ADMINISTRATOR: [
    ACADEMIC_CYCLE_PERMISSIONS.MANAGE_ACADEMIC_CYCLES,
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_ALL_ACADEMIC_CYCLES,
    // Social Wall - Full access
    SOCIAL_WALL_PERMISSIONS.CREATE_POST,
    SOCIAL_WALL_PERMISSIONS.CREATE_ACHIEVEMENT_POST,
    SOCIAL_WALL_PERMISSIONS.UPDATE_POST,
    SOCIAL_WALL_PERMISSIONS.DELETE_POST,
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.CREATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.UPDATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.DELETE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
    SOCIAL_WALL_PERMISSIONS.TAG_USERS,
    SOCIAL_WALL_PERMISSIONS.MODERATE_CONTENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_MODERATION_LOGS,
  ] as const,

  // Campus Level
  CAMPUS_ADMIN: [
    ACADEMIC_CYCLE_PERMISSIONS.MANAGE_CAMPUS_ACADEMIC_CYCLES,
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CAMPUS_ACADEMIC_CYCLES,
    // Social Wall - Full access
    SOCIAL_WALL_PERMISSIONS.CREATE_POST,
    SOCIAL_WALL_PERMISSIONS.CREATE_ACHIEVEMENT_POST,
    SOCIAL_WALL_PERMISSIONS.UPDATE_POST,
    SOCIAL_WALL_PERMISSIONS.DELETE_POST,
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.CREATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.UPDATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.DELETE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
    SOCIAL_WALL_PERMISSIONS.TAG_USERS,
    SOCIAL_WALL_PERMISSIONS.MODERATE_CONTENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_MODERATION_LOGS,
  ] as const,

  CAMPUS_COORDINATOR: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CAMPUS_ACADEMIC_CYCLES,
    // Social Wall - Teacher level access
    SOCIAL_WALL_PERMISSIONS.CREATE_POST,
    SOCIAL_WALL_PERMISSIONS.CREATE_ACHIEVEMENT_POST,
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.CREATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
    SOCIAL_WALL_PERMISSIONS.TAG_USERS,
    SOCIAL_WALL_PERMISSIONS.MODERATE_CONTENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_MODERATION_LOGS,
  ] as const,

  CAMPUS_PRINCIPAL: [
    ACADEMIC_CYCLE_PERMISSIONS.MANAGE_CAMPUS_ACADEMIC_CYCLES,
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CAMPUS_ACADEMIC_CYCLES,
    // Social Wall - Full access
    SOCIAL_WALL_PERMISSIONS.CREATE_POST,
    SOCIAL_WALL_PERMISSIONS.CREATE_ACHIEVEMENT_POST,
    SOCIAL_WALL_PERMISSIONS.UPDATE_POST,
    SOCIAL_WALL_PERMISSIONS.DELETE_POST,
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.CREATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.UPDATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.DELETE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
    SOCIAL_WALL_PERMISSIONS.TAG_USERS,
    SOCIAL_WALL_PERMISSIONS.MODERATE_CONTENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_MODERATION_LOGS,
  ] as const,

  COORDINATOR: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CAMPUS_ACADEMIC_CYCLES,
    // Social Wall - Teacher level access
    SOCIAL_WALL_PERMISSIONS.CREATE_POST,
    SOCIAL_WALL_PERMISSIONS.CREATE_ACHIEVEMENT_POST,
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.CREATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
    SOCIAL_WALL_PERMISSIONS.TAG_USERS,
    SOCIAL_WALL_PERMISSIONS.MODERATE_CONTENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_MODERATION_LOGS,
  ] as const,

  // Academic Roles
  TEACHER: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CLASS_ACADEMIC_CYCLES,
    // Social Wall - Teacher access
    SOCIAL_WALL_PERMISSIONS.CREATE_POST,
    SOCIAL_WALL_PERMISSIONS.CREATE_ACHIEVEMENT_POST,
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.CREATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
    SOCIAL_WALL_PERMISSIONS.TAG_USERS,
    SOCIAL_WALL_PERMISSIONS.MODERATE_CONTENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_MODERATION_LOGS,
  ] as const,

  CAMPUS_TEACHER: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CLASS_ACADEMIC_CYCLES,
    TEACHER_ROLE_PERMISSIONS.CLASS_TEACHER_ACCESS,
    TEACHER_ROLE_PERMISSIONS.CLASS_TEACHER_GRADE_OVERRIDE,
    TEACHER_ROLE_PERMISSIONS.SUBJECT_TEACHER_ACCESS,
    TEACHER_ROLE_PERMISSIONS.SUBJECT_TEACHER_GRADE,
    // Social Wall - Teacher access
    SOCIAL_WALL_PERMISSIONS.CREATE_POST,
    SOCIAL_WALL_PERMISSIONS.CREATE_ACHIEVEMENT_POST,
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.CREATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
    SOCIAL_WALL_PERMISSIONS.TAG_USERS,
    SOCIAL_WALL_PERMISSIONS.MODERATE_CONTENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_MODERATION_LOGS,
  ] as const,

  // Student Roles
  STUDENT: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CLASS_ACADEMIC_CYCLES,
    // Social Wall - Student access
    SOCIAL_WALL_PERMISSIONS.CREATE_ACHIEVEMENT_POST,
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.CREATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
    SOCIAL_WALL_PERMISSIONS.TAG_USERS,
  ] as const,

  CAMPUS_STUDENT: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CLASS_ACADEMIC_CYCLES,
    // Social Wall - Student access
    SOCIAL_WALL_PERMISSIONS.CREATE_ACHIEVEMENT_POST,
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.CREATE_COMMENT,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
    SOCIAL_WALL_PERMISSIONS.TAG_USERS,
  ] as const,

  // Other Roles
  CAMPUS_PARENT: [
    ACADEMIC_CYCLE_PERMISSIONS.VIEW_CLASS_ACADEMIC_CYCLES,
    // Social Wall - View only access
    SOCIAL_WALL_PERMISSIONS.VIEW_POSTS,
    SOCIAL_WALL_PERMISSIONS.VIEW_COMMENTS,
    SOCIAL_WALL_PERMISSIONS.ADD_REACTION,
    SOCIAL_WALL_PERMISSIONS.REMOVE_REACTION,
  ] as const,
} as const;